<?php

return [

    'arrayUsers' => [
            [
                'name' => 'gianluca',
                'surname' => 'gioacchino',
                'telephone_number' => '3347010952',
                'email' => 'gianluca@gmail.com',
                'password' => 'password',
                'business_name' => "Mc. Donalds Milano",
                'cover_img' => "uploads/mcdonalds.jpg",
                'city' => "Milano",
                'zip_code' => "20019",
                'address' => 'Via Giordano Bruno 40',
                'vat_number' => '12345678911',
            ],
            [
                'name' => 'Alessandro',
                'surname' => 'Guerri',
                'telephone_number' => '3347592365',
                'email' => 'guerri@gmail.com',
                'password' => 'password',
                'business_name' => "Poke",
                'cover_img' => "uploads/pokeyou.jpg",
                'city' => "Milano",
                'zip_code' => "20019",
                'address' => 'Via Roma 22',
                'vat_number' => '45632587894',
            ],
            [
                'name' => 'Roberto',
                'surname' => 'Carlos',
                'telephone_number' => '3348520594',
                'email' => 'carlos@gmail.com',
                'password' => 'password',
                'business_name' => "Old Wild West",
                'cover_img' => "uploads/oldwildwest.jpg",
                'city' => "Milano",
                'zip_code' => "20021",
                'address' => 'Via Trento Trieste 19',
                'vat_number' => '1658256985',
            ],
            [
                'name' => 'Nicola',
                'surname' => 'Peggiore',
                'telephone_number' => '3348090666',
                'email' => 'peggiore@gmail.com',
                'password' => 'password',
                'business_name' => "Pizzeria Alice",
                'cover_img' => "uploads/alice-pizza.jpg",
                'city' => "Milano",
                'zip_code' => "20068",
                'address' => 'Via Cimabue 62',
                'vat_number' => '95635489752',
            ],
            [
                'name' => 'Antonio',
                'surname' => 'Siculo',
                'telephone_number' => '3342050511',
                'email' => 'Siculo@gmail.com',
                'password' => 'password',
                'business_name' => "Dominos",
                'cover_img' => "uploads/dominos-pizza.jpg",
                'city' => "Milano",
                'zip_code' => "20089",
                'address' => 'Via Garibaldi 29',
                'vat_number' => '52185698514',
            ],
            [
                'name' => 'Andrea',
                'surname' => 'Castracani',
                'telephone_number' => '3348509521',
                'email' => 'castracani@gmail.com',
                'password' => 'password',
                'business_name' => "Ristorante Bosco Verticale",
                'cover_img' => "uploads/ristorante-bosco-verticale.jpg",
                'city' => "Milano",
                'zip_code' => "20122",
                'address' => 'Via Vittorio Emanuele',
                'vat_number' => '85364895200',
            ],
            [
                'name' => 'Andrea',
                'surname' => 'Soffiantini',
                'telephone_number' => '3349599852',
                'email' => 'soffiantini@gmail.com',
                'password' => 'password',
                'business_name' => "Trattoria Trippa",
                'cover_img' => "uploads/trippamilanotrattoria.jpg",
                'city' => "Milano",
                'zip_code' => "20126",
                'address' => 'Via Tiziano 10',
                'vat_number' => '00587468951',
            ],
            [
                'name' => 'Fabio',
                'surname' => 'Pacifici',
                'telephone_number' => '3348080951',
                'email' => 'fabiohood@gmail.com',
                'password' => 'password',
                'business_name' => "Izu Milano",
                'cover_img' => "uploads/izumilano.jpg",
                'city' => "Milano",
                'zip_code' => "20091",
                'address' => 'Viale Pacifici 22',
                'vat_number' => '78945612307',
            ],
            [
                'name' => 'Tiziano',
                'surname' => 'Nicolai',
                'telephone_number' => '3346610330',
                'email' => 'tiziano.nicolai@gmail.com',
                'password' => 'password',
                'business_name' => "Iyo",
                'cover_img' => "uploads/iyomilano.jpg",
                'city' => "Milano",
                'zip_code' => "20090",
                'address' => 'Via Alessandro dal Borro 5',
                'vat_number' => '44489635897',
            ],
            [
                'name' => 'Martina',
                'surname' => 'Mussi',
                'telephone_number' => '3347070778',
                'email' => 'mussi@gmail.com',
                'password' => 'password',
                'business_name' => "Langosteria",
                'cover_img' => "uploads/Langosteria.jpg",
                'city' => "Milano",
                'zip_code' => "20026",
                'address' => 'Via Gramsci 62',
                'vat_number' => '46317968520',
            ],
            [
                'name' => 'Fabiola',
                'surname' => 'Gardin',
                'telephone_number' => '3347082934',
                'email' => 'fabiolag@gmail.com',
                'password' => 'password',
                'business_name' => "Lasagna factory",
                'cover_img' => "uploads/lasagnafactorymilano.jpg",
                'city' => "Milano",
                'zip_code' => "20057",
                'address' => 'Via Giolitti 29',
                'vat_number' => '78902589614',
            ],
            [
                'name' => 'Simone',
                'surname' => 'Coccolicchio',
                'telephone_number' => '3349910335',
                'email' => 'simo.cocco@gmail.com',
                'password' => 'password',
                'business_name' => "Fishbar de Milan",
                'cover_img' => "uploads/fishbardemilan.jpg",
                'city' => "Milano",
                'zip_code' => "20019",
                'address' => 'Via Fiorentina 73',
                'vat_number' => '73917594628',
            ],
            [
                'name' => 'Romeo',
                'surname' => 'Carlomusto',
                'telephone_number' => '3346060001',
                'email' => 'carlomusto@gmail.com',
                'password' => 'password',
                'business_name' => "Il Panino",
                'cover_img' => "uploads/il_panino_milano.jpg",
                'city' => "Milano",
                'zip_code' => "20123",
                'address' => 'Via parco verde 46',
                'vat_number' => '82719634862',
            ],
            [
                'name' => 'Matteo',
                'surname' => 'Giannetti',
                'telephone_number' => '3345656663',
                'email' => 'giannetti@gmail.com',
                'password' => 'password',
                'business_name' => "Poke House",
                'cover_img' => "uploads/pokehouse.jpg",
                'city' => "Milano",
                'zip_code' => "20123",
                'address' => 'Via porta buia 29',
                'vat_number' => '75335789512',
            ],
            [
                'name' => 'Alessio',
                'surname' => 'Riccardi',
                'telephone_number' => '3347010954',
                'email' => 'riccardi@gmail.com',
                'password' => 'password',
                'business_name' => "Bottega Sicula Pescheria",
                'cover_img' => "uploads/bottega-sicula.jpg",
                'city' => "Milano",
                'zip_code' => "20122",
                'address' => 'Via Romana 82',
                'vat_number' => '16579463255',
            ],
            [
                'name' => 'Mirna',
                'surname' => 'Senserini',
                'telephone_number' => '3349660557',
                'email' => 'senserini@gmail.com',
                'password' => 'password',
                'business_name' => "Levino Milano",
                'cover_img' => "uploads/levino-milano.jpg",
                'city' => "Milano",
                'zip_code' => "20122",
                'address' => 'Viale Europa 21',
                'vat_number' => '42896358741',
            ],
            [
                'name' => 'Viktor',
                'surname' => 'Barca',
                'telephone_number' => '3342001485',
                'email' => 'barcavik@gmail.com',
                'password' => 'password',
                'business_name' => "Cantine Milano Ristorante e Wine Bar",
                'cover_img' => "uploads/cantinemilano.jpg",
                'city' => "Milano",
                'zip_code' => "20133",
                'address' => 'Via Giovanni Paolo 2',
                'vat_number' => '13289473284',
            ],
            [
                'name' => 'Alessandro',
                'surname' => 'Borghesi',
                'telephone_number' => '3349992547',
                'email' => 'borghesi.alessandro@gmail.com',
                'password' => 'password',
                'business_name' => "Lon fon",
                'cover_img' => "uploads/lonfon.jpg",
                'city' => "Milano",
                'zip_code' => "20133",
                'address' => 'Via Napoli 41',
                'vat_number' => '16897459875',
            ],
            [
                'name' => 'Tino',
                'surname' => 'Capua',
                'telephone_number' => '3341256753',
                'email' => 'tinocapua@gmail.com',
                'password' => 'password',
                'business_name' => "Yeubinlou",
                'cover_img' => "uploads/Yeubinlou.jpg",
                'city' => "Milano",
                'zip_code' => "20133",
                'address' => 'Via Cavour 42',
                'vat_number' => '25896336902',
            ],
            [
                'name' => 'Rosa',
                'surname' => 'Migliore',
                'telephone_number' => '3347050669',
                'email' => 'rosaMigliore@gmail.com',
                'password' => 'password',
                'business_name' => "Ba Ba Reeba",
                'cover_img' => "uploads/babareeba.jpg",
                'city' => "Milano",
                'zip_code' => "20089",
                'address' => 'Via Teano 12',
                'vat_number' => '12005498765',
            ],
        ],

        // Array types
        'arrayTypes' => [
            [
                'name' => 'Internazionale',
            ],

            [
                'name' => 'Italiano',
            ],

            [
                'name' => 'Giapponese',
            ],

            [
                'name' => 'Cinese',
            ],

            [
                'name' => 'Indiano',
            ],

            [
                'name' => 'Messicano',
            ],

            [
                'name' => 'Americano',
            ],

            [
                'name' => 'Pesce',
            ],

            [
                'name' => 'Steak House',
            ],

            [
                'name' => 'Greco',
            ],

            [
                'name' => 'Pizzeria',
            ],

            [
                'name' => 'Bar',
            ],

            [
                'name' => 'Fast-Food',
            ],

            [
                'name' => 'All you can eat',
            ],

            [
                'name' => 'Spagnolo',
            ],
        ]
    ];

?>
